### ISSUE TITLE
Cards previously encoded no longer work after being placed into a deck

### ISSUE THREAD

**Issue by Babyboodle** [Jophire/Tabletop-Simulator-Workshop-Items#3]
Hi there! This is the same Babyboodle from Steam who was asking you about your encoder a while ago. I wanted to point out a bug when implementing this version of the core. When you take a card out of a stack and set it onto the table, it'll successfully render the encoder menu onto the card. However, if you place that same card back into a stack and place it onto the table again, it will no longer render the encoder menu on the card until you clone it as a new object. If you can recreate it, cool! Otherwise let me know if it's something on my end and you can just close this issue report.

**Comment by Jophire** [comment]
Another method to fix instead of cloning the card is to put it into a handzone and drop it again. Will look into this closer.

**Comment by Jophire** [comment]
Should be fixed, sorry for the wait.
